sudo: false
dist: trusty
os: linux

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.3-bin.zip
  - unzip -qq gradle-6.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - chmod +x gradlew

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: smoke
      script: gradle clean runTests -Dtag=SMOKE -DslackNotif=automation
    - stage: regression
      script: gradle clean runTestsParallel -Dtag=REGRESSION -DslackNotif=automation