sudo: false
dist: xenial
os: linux

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - gradle gwrapper
  - chmod +x gradlew

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: smoke
      script: gradle clean runTests -Dtag=SMOKE -DslackNotif=automation
    - stage: regression
      script: gradle clean runTestsParallel -Dtag=REGRESSION -DslackNotif=automation